#pragma config(StandardModel, "RVW REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*+++++++++++++++++++++++++++++++++++++++++++++| Notes |++++++++++++++++++++++++++++++++++++++++++++++
2 Joystick Drive
- This program allows you to remotely control your robot using the USB Logitech Dual
  Action Joysticks.
- For USB values to be transmitted to the robot, you must follow several steps:
  - Use the "#include "JoystickDriver.c"" line at the beginning of your program
  - Call the "getJoystickSettings(joystick);" in a loop to repeatedly retrieve the latest values
  - Open the Robot > Debugger Windows > "Joystick Control - Basic" window after downloading your
    program to the virtual robot
----------------------------------------------------------------------------------------------------*/

#pragma debuggerWindows("joystickSimple");
#include "JoystickDriver.c"

task main()
{
	int deadzone = 20;
  //Loop Forever
  while(true)
  {
    //Get the Latest joystick values
    getJoystickSettings(joystick);
    if(abs(joystick.joy1_y1) > deadzone){
    	if(joystick.joy1_y2 > 0){
    		motor[leftMotor] = (joystick.joy1_y1 + 100);
    	}else{
    		motor[leftMotor] = (joystick.joy1_y1 - 100 );
    	}
  	}
    if(abs(joystick.joy1_y2) > deadzone){
	    //Set the driving motors equal to the Y-axis values of the joysticks
    	if(joystick.joy1_y2 > 0){
    		motor[rightMotor] = (joystick.joy1_y2 + 100);
    	}else{
    		motor[rightMotor] = (joystick.joy1_y2 - 100 );
    	}
    	wait1Msec(10);
    }
  	if(abs(joystick.joy1_y1)<deadzone || abs(joystick.joy1_y2)<deadzone){
  		motor[leftMotor] = 0;
  		motor[rightMotor] = 0;
  	}
  	if(joy1Btn(7) == 1){
  		 motor[gripperMotor] = 20;
  		 wait1Msec(200);
  		 motor[gripperMotor] = 0;
  	}
  	if(joy1Btn(8) == 1){
  		motor[gripperMotor] = -30;
  		wait1Msec(200);
  		motor[gripperMotor] = 0;
  	}
//beep beep beep

  }
}
